---
Kilburn_SROS:
  hostname: 192.168.255.123
  platform: UNKNOWN_VENDOR
  groups:
    - NOKIA
  data:
    region: west-region
    operation: netconf-enabled

###R2_SROS:
###  hostname: 192.168.0.210
###  groups:
###    - NOKIA
###
###R3_CSR:
###  hostname: 192.168.0.223
###  groups:
###    - CSR
###
###R3_SROS_PE:
###  hostname: 192.168.0.222
###  groups:
###    - NOKIA
###  data:
###    region: west-region
###    operation: netconf-enabled
